name = "5dice-backend"
main = "worker.js"
compatibility_date = "2024-03-20"

[[kv_namespaces]]
binding = "FIVEDICE_KV"
id = "preview_kv_id" # This needs to be replaced with real KV id in prod
preview_id = "preview_kv_id"
